from voice_assistant.app_interfaces.i_command_performer import ICommandPerformer
from voice_assistant.app_interfaces.i_message_recognizer import IMessageRecognizer
from voice_assistant.app_interfaces.i_topic_definer import ITopicDefiner
