"""Initial

Revision ID: c98cce3bd58f
Revises:
Create Date: 2025-08-02 17:40:44.006503

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c98cce3bd58f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contex",
        sa.Column("session_name", sa.String(), nullable=False),
        sa.Column("last_activity_topic", sa.String(), nullable=True),
        sa.Column("last_activity_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("session_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contex")
    # ### end Alembic commands ###
