"""Initial

Revision ID: cc77b6120219
Revises:
Create Date: 2025-08-01 21:19:48.097472

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc77b6120219"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contex",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_activity_topic", sa.String(), nullable=True),
        sa.Column("last_activity_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contex")
    # ### end Alembic commands ###
