"""calendar data

Revision ID: faeab7b7a397
Revises: c98cce3bd58f
Create Date: 2025-08-02 20:41:26.286045

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faeab7b7a397"
down_revision: str | Sequence[str] | None = "c98cce3bd58f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_data",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("token_data", sa.JSON(), nullable=True),
        sa.Column("calendar_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_data")
    # ### end Alembic commands ###
